config/routes.rb
Rails.application.routes.draw do
  resources :holidays
  resources :leave_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/holiday.rb
class Holiday < ApplicationRecord
end

app/models/leave_type.rb
class LeaveType < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :set_holiday, only: [:show, :edit, :update, :destroy]

  # GET /holidays
  # GET /holidays.json
  def index
    @holidays = Holiday.all
  end

  # GET /holidays/1
  # GET /holidays/1.json
  def show
  end

  # GET /holidays/new
  def new
    @holiday = Holiday.new
  end

  # GET /holidays/1/edit
  def edit
  end

  # POST /holidays
  # POST /holidays.json
  def create
    @holiday = Holiday.new(holiday_params)

    respond_to do |format|
      if @holiday.save
        format.html { redirect_to @holiday, notice: 'Holiday was successfully created.' }
        format.json { render :show, status: :created, location: @holiday }
      else
        format.html { render :new }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holidays/1
  # PATCH/PUT /holidays/1.json
  def update
    respond_to do |format|
      if @holiday.update(holiday_params)
        format.html { redirect_to @holiday, notice: 'Holiday was successfully updated.' }
        format.json { render :show, status: :ok, location: @holiday }
      else
        format.html { render :edit }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holidays/1
  # DELETE /holidays/1.json
  def destroy
    @holiday.destroy
    respond_to do |format|
      format.html { redirect_to holidays_url, notice: 'Holiday was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_holiday
      @holiday = Holiday.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def holiday_params
      params.require(:holiday).permit(:name, :holiday_date)
    end
end

app/controllers/leave_types_controller.rb
class LeaveTypesController < ApplicationController
  before_action :set_leave_type, only: [:show, :edit, :update, :destroy]

  # GET /leave_types
  # GET /leave_types.json
  def index
    @leave_types = LeaveType.all
  end

  # GET /leave_types/1
  # GET /leave_types/1.json
  def show
  end

  # GET /leave_types/new
  def new
    @leave_type = LeaveType.new
  end

  # GET /leave_types/1/edit
  def edit
  end

  # POST /leave_types
  # POST /leave_types.json
  def create
    @leave_type = LeaveType.new(leave_type_params)

    respond_to do |format|
      if @leave_type.save
        format.html { redirect_to @leave_type, notice: 'Leave type was successfully created.' }
        format.json { render :show, status: :created, location: @leave_type }
      else
        format.html { render :new }
        format.json { render json: @leave_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leave_types/1
  # PATCH/PUT /leave_types/1.json
  def update
    respond_to do |format|
      if @leave_type.update(leave_type_params)
        format.html { redirect_to @leave_type, notice: 'Leave type was successfully updated.' }
        format.json { render :show, status: :ok, location: @leave_type }
      else
        format.html { render :edit }
        format.json { render json: @leave_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leave_types/1
  # DELETE /leave_types/1.json
  def destroy
    @leave_type.destroy
    respond_to do |format|
      format.html { redirect_to leave_types_url, notice: 'Leave type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leave_type
      @leave_type = LeaveType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def leave_type_params
      params.require(:leave_type).permit(:name, :descripton)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/helpers/leave_types_helper.rb
module LeaveTypesHelper
end

app/views/holidays/_form.html.erb
<%= form_for(holiday) do |f| %>
  <% if holiday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(holiday.errors.count, "error") %> prohibited this holiday from being saved:</h2>

      <ul>
      <% holiday.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :holiday_date %>
    <%= f.text_field :holiday_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/holidays/edit.html.erb
<h1>Editing Holiday</h1>

<%= render 'form', holiday: @holiday %>

<%= link_to 'Show', @holiday %> |
<%= link_to 'Back', holidays_path %>

app/views/holidays/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Holidays</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Holiday date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @holidays.each do |holiday| %>
      <tr>
        <td><%= holiday.name %></td>
        <td><%= holiday.holiday_date %></td>
        <td><%= link_to 'Show', holiday %></td>
        <td><%= link_to 'Edit', edit_holiday_path(holiday) %></td>
        <td><%= link_to 'Destroy', holiday, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Holiday', new_holiday_path %>

app/views/holidays/new.html.erb
<h1>New Holiday</h1>

<%= render 'form', holiday: @holiday %>

<%= link_to 'Back', holidays_path %>

app/views/holidays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @holiday.name %>
</p>

<p>
  <strong>Holiday date:</strong>
  <%= @holiday.holiday_date %>
</p>

<%= link_to 'Edit', edit_holiday_path(@holiday) %> |
<%= link_to 'Back', holidays_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LmsApi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/leave_types/_form.html.erb
<%= form_for(leave_type) do |f| %>
  <% if leave_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(leave_type.errors.count, "error") %> prohibited this leave_type from being saved:</h2>

      <ul>
      <% leave_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :descripton %>
    <%= f.text_area :descripton %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leave_types/edit.html.erb
<h1>Editing Leave Type</h1>

<%= render 'form', leave_type: @leave_type %>

<%= link_to 'Show', @leave_type %> |
<%= link_to 'Back', leave_types_path %>

app/views/leave_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Leave Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Descripton</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leave_types.each do |leave_type| %>
      <tr>
        <td><%= leave_type.name %></td>
        <td><%= leave_type.descripton %></td>
        <td><%= link_to 'Show', leave_type %></td>
        <td><%= link_to 'Edit', edit_leave_type_path(leave_type) %></td>
        <td><%= link_to 'Destroy', leave_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Leave Type', new_leave_type_path %>

app/views/leave_types/new.html.erb
<h1>New Leave Type</h1>

<%= render 'form', leave_type: @leave_type %>

<%= link_to 'Back', leave_types_path %>

app/views/leave_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @leave_type.name %>
</p>

<p>
  <strong>Descripton:</strong>
  <%= @leave_type.descripton %>
</p>

<%= link_to 'Edit', edit_leave_type_path(@leave_type) %> |
<%= link_to 'Back', leave_types_path %>